import type { CapacitorConfig } from '@capacitor/cli';

/**
 * Capacitor configuration for the Rowly native app shell.
 *
 * The native projects (ios/, android/) are generated by running:
 *   npm run cap:add:ios
 *   npm run cap:add:android
 * …once Xcode + CocoaPods (iOS) and Android Studio (Android) are installed
 * locally. See docs/capacitor.md for the full setup.
 *
 * The web side bundles via `npm run build` into frontend/dist; Capacitor
 * copies that into the native containers on `npm run cap:sync`.
 */
const config: CapacitorConfig = {
  // Reverse-DNS app ID, shared between iOS + Android. Changing this after
  // publishing would create a new app in the stores, so it's fixed now.
  appId: 'com.rowlyknit.app',
  appName: 'Rowly',
  // Vite's production build outputs to dist/; Capacitor copies from here
  // into ios/App/App/public and android/app/src/main/assets/public.
  webDir: 'dist',
  // Background color shown during splash / behind the web view on iOS
  // before content paints; matches the app's purple theme.
  backgroundColor: '#faf7ff',
  // Server options are deliberately empty — in production the app loads
  // bundled assets, not a remote server. During local dev you can override
  // with CAPACITOR_SERVER_URL (see docs/capacitor.md).
  server: undefined,
};

export default config;
