/**
 * Normalized public-tool result shape — Sprint 1 Public Tools Conversion.
 *
 * Every public calculator emits a `ToolResult` regardless of the tool.
 * The shape is what flows through the save-to-Rowly pipeline:
 *
 *     calculator → ToolResult → pendingSave (localStorage) → SaveCTA
 *                                                          → entitlement gate
 *                                                          → POST /api/projects/:id/memos
 *
 * Why a single shape:
 *   - One serializer / deserializer for the localStorage resume flow.
 *   - One backend memo schema (the `data` blob on `structured_memos`)
 *     that downstream UI surfaces (project memo list, future stash UI,
 *     future Make Mode draft view) read uniformly.
 *   - One analytics event (`tool_result_saved`) with a `toolId` prop.
 *
 * The discriminated union on `result` keeps each tool's payload
 * type-safe at its own boundary while letting the shared CTA stay
 * generic. Tools may extend their result with additional fields, but
 * MUST keep the existing keys stable across releases — old saved memos
 * will round-trip through new code.
 */

import type { ToolId, SaveTarget } from './publicTools';

/** ISO-8601 string. */
export type IsoString = string;

export interface ToolResultBase<TInputs, TResult> {
  toolId: ToolId;
  /**
   * Bumped by the tool author when the inputs/result schema changes
   * incompatibly. The save flow stores it on the memo so future
   * readers can refuse / migrate stale shapes gracefully.
   */
  toolVersion: string;
  inputs: TInputs;
  result: TResult;
  /**
   * One-line plain-English summary suitable for a memo title or list
   * row. Generated by the tool itself — the tool knows the user's
   * preferred units / wording better than the save flow does.
   * Example: "5 sts/inch on US 7 — 0.5 sts/inch tighter than pattern"
   */
  humanSummary: string;
  /**
   * Save targets the tool considers appropriate. Subset of the registry's
   * `saveTargets`. The picker uses this to grey out destinations that
   * don't make sense for this specific result (e.g. yardage might
   * support `stash` but a row-repeat result shouldn't).
   */
  recommendedSaveTargets: SaveTarget[];
  createdAt: IsoString;
}

// =============================================================
// Per-tool result types — the discriminator union
// =============================================================

export interface GaugeResult {
  status: 'on_gauge' | 'tight' | 'loose';
  userStitchesPerInch: number;
  userRowsPerInch: number;
  patternStitchesPerInch: number;
  patternRowsPerInch: number;
  driftStitchesPerInch: number;
  driftRowsPerInch: number;
  needleSize?: string;
  stitchPattern?: string;
}

export interface SizeResult {
  recipientChestIn: number;
  fit: 'fitted' | 'classic' | 'relaxed' | 'oversized';
  recommendations: Array<{
    scheme: 'women' | 'men' | 'children' | 'baby';
    size: string;
    finishedChestIn: number;
    easeIn: number;
  }>;
}

export interface YardageResult {
  garmentType:
    | 'hat'
    | 'scarf'
    | 'cowl'
    | 'mittens'
    | 'socks'
    | 'shawl'
    | 'sweater_adult'
    | 'sweater_child'
    | 'baby_blanket'
    | 'throw_blanket';
  yarnWeight:
    | 'lace'
    | 'fingering'
    | 'sport'
    | 'dk'
    | 'worsted'
    | 'aran'
    | 'bulky'
    | 'super_bulky';
  size: 'xs' | 's' | 'm' | 'l' | 'xl' | 'xxl' | 'one_size';
  estimatedYards: number;
  estimatedMeters: number;
  skeinsAt200Yd: number;
  rangeLowYards: number;
  rangeHighYards: number;
}

export interface RowRepeatResult {
  totalRowsAvailable: number;
  rowsPerRepeat: number;
  fullRepeats: number;
  remainderRows: number;
  fitsCleanly: boolean;
  endsAtRow: number;
}

export interface ShapingResult {
  startStitches: number;
  endStitches: number;
  totalRows: number;
  shapingType: 'increase' | 'decrease';
  totalShapingChanges: number;
  /**
   * Plain-English instruction. Always two values when the math doesn't
   * divide evenly:
   *   "Decrease every 8 rows X times, then every 9 rows Y times"
   * One value when it does:
   *   "Decrease every 8 rows 12 times"
   */
  instruction: string;
  intervalA: number;
  countA: number;
  intervalB: number | null;
  countB: number | null;
}

// =============================================================
// Discriminated union — what callers consume
// =============================================================

export type ToolResult =
  | (ToolResultBase<Record<string, unknown>, GaugeResult> & { toolId: 'gauge' })
  | (ToolResultBase<Record<string, unknown>, SizeResult> & { toolId: 'size' })
  | (ToolResultBase<Record<string, unknown>, YardageResult> & { toolId: 'yardage' })
  | (ToolResultBase<Record<string, unknown>, RowRepeatResult> & {
      toolId: 'row-repeat';
    })
  | (ToolResultBase<Record<string, unknown>, ShapingResult> & { toolId: 'shaping' });

/**
 * Map a tool's result to the backend `structured_memos.template_type`
 * value. Sprint 1 stores all save destinations as project memos with
 * destination-specific template types — the future UI surfaces (stash,
 * pattern detail, Make Mode) filter memos by this column.
 */
export function templateTypeFor(
  toolId: ToolId,
  destination: SaveTarget,
): string {
  if (toolId === 'gauge' && destination === 'project') return 'calculator_result';
  if (toolId === 'gauge' && destination === 'pattern') return 'gauge_swatch';
  if (toolId === 'size') return 'fit_adjustment';
  if (toolId === 'yardage' && destination === 'stash') return 'stash_estimate';
  if (toolId === 'yardage') return 'yardage_estimate';
  if (toolId === 'row-repeat' && destination === 'make-mode')
    return 'make_mode_reminder';
  if (toolId === 'row-repeat') return 'row_repeat_plan';
  if (toolId === 'shaping' && destination === 'make-mode')
    return 'make_mode_reminder';
  if (toolId === 'shaping') return 'shaping_plan';
  return 'calculator_result';
}
